# Generated by Django 4.2.19 on 2025-02-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
