# Generated by Django 4.2.19 on 2025-03-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlists', '0003_waitlistentry_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitlistentry',
            old_name='update',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
